objects/Laser_Artwork_Order__c.object
<CustomObject>
    <description>NOTE: Removing or changing the prefix before the Name (&quot;LAO - &quot;) requires changing the DS_LAO_Operations Apex Class.</description>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Forms_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_ID_RMS_Link__c</fullName>
        <formula>hyperlink(&quot;http://&quot; &amp; $Setup.CustomSettings__c.RMS_Request_Link__c &amp; Request_ID_RMS__c, Request_ID_RMS__c,&quot;_blank&quot;)</formula>
        <label>Request ID (RMS) Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_ID_RMS__c</fullName>
        <label>Request ID (RMS)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Forms Order</label>
    <nameField>
        <displayFormat>FO - {0000000}</displayFormat>
        <label>Art Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SubProject__c.object
<CustomObject>
    <description>Subproject contains project information related to project type and/or product(s), as well as milestones, project logs and additional details;  rolls up to the Project.</description>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confidential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Roll_Called__c</fullName>
        <label>Contract Roll Called</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Go_Live_Date__c</fullName>
        <label>Go-Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Impact_Project_Numbers__c</fullName>
        <label>Impact Project Number(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SubProjectsMgrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubProject</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>SubProject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SubProject_External_Reference__c.object
<CustomObject>
    <description>This object is used to store the Lookup relationships to external objects that are related to the Sub-Project like the Laser Artwork Order, NIS Mission etc.</description>
    <fields>
        <fullName>LAO_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the LAO Object</description>
        <label>LAO ID</label>
        <referenceTo>Laser_Artwork_Order__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubProject__c</fullName>
        <label>SubProject</label>
        <referenceTo>SubProject__c</referenceTo>
        <relationshipLabel>SubProject External References</relationshipLabel>
        <relationshipName>SubProject_External_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SubProject External Reference</label>
    <nameField>
        <displayFormat>SPER-{0000000}</displayFormat>
        <label>External Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubProject External References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Subproject_On_Laser_Extension.cls
/*------------------------------------------------------------
Author:        Vishal Bandari
Description:   Extension for Subproject_On_LAO Visual Force Page
Created on:    30 July 2015.
Test Class:    IMP_UpdateFormsOrder_Test
Code Coverage: 100%
------------------------------------------------------------
History
30 July 2015    Vishal Bandari      RQ-04982: Added getRecordDetails method
------------------------------------------------------------*/
public class Subproject_On_Laser_Extension
{
    private Id LAO_RecordId;
    
    public SubProject_External_Reference__c sperObj {get;set;}
    
    public Laser_Artwork_Order__c laoObj{get;set;}
    
    public Subproject_On_Laser_Extension(ApexPages.StandardController stdController)
    {
        LAO_RecordId = stdController.getId();
    }
    
    public void getRecordDetails()
    {
        try
        {
            laoObj = [
                SELECT Id, Request_ID_RMS__c, Request_ID_RMS_Link__c 
                FROM Laser_Artwork_Order__c 
                WHERE Id =: LAO_RecordId
            ];
            
            sperObj = [
                SELECT SubProject__c,SubProject__r.Confidential__c,SubProject__r.Name, SubProject__r.Go_Live_Date__c, SubProject__r.Project_Manager__c, 
                SubProject__r.Impact_Project_Numbers__c, SubProject__r.Contract_Roll_Called__c
                FROM SubProject_External_Reference__c 
                WHERE LAO_ID__c =: LAO_RecordId
            ];  
        }
        catch(Exception e)
        {
            System.debug('Exception: '+e.getMessage()+' At '+e.getLineNumber());
        }
    }
    public PageReference save()
    {
        update laoObj;
        laoObj = [
            SELECT Id, Request_ID_RMS__c, Request_ID_RMS_Link__c 
            FROM Laser_Artwork_Order__c 
            WHERE Id =: LAO_RecordId
        ];
        return null;
    }
    public PageReference cancel()
    {
        return null;
    }
}